[workspace]
members = ["ooniauth-core", "ooniauth-py"]
resolver = "2"

[workspace.dependencies]
rand = "0.8.5"
bincode = "1"
# cmz = "0.1.0"
cmz = {git = "https://github.com/sigma-rs/cmz"}
serde = "1.0.219"
thiserror = "2.0.12"

